/* tslint:disable */
/* eslint-disable */
import { Assembly } from './assembly';
import { ConstructorInfo } from './constructor-info';
import { CustomAttributeData } from './custom-attribute-data';
import { GenericParameterAttributes } from './generic-parameter-attributes';
import { MemberTypes } from './member-types';
import { MethodBase } from './method-base';
import { Module } from './module';
import { RuntimeTypeHandle } from './runtime-type-handle';
import { StructLayoutAttribute } from './struct-layout-attribute';
import { TypeAttributes } from './type-attributes';
export interface Type {
  Assembly?: Assembly;
  AssemblyQualifiedName?: null | string;
  Attributes?: TypeAttributes;
  BaseType?: Type;
  ContainsGenericParameters?: boolean;
  CustomAttributes?: null | Array<CustomAttributeData>;
  DeclaringMethod?: MethodBase;
  DeclaringType?: Type;
  FullName?: null | string;
  GUID?: string;
  GenericParameterAttributes?: GenericParameterAttributes;
  GenericParameterPosition?: number;
  GenericTypeArguments?: null | Array<Type>;
  HasElementType?: boolean;
  IsAbstract?: boolean;
  IsAnsiClass?: boolean;
  IsArray?: boolean;
  IsAutoClass?: boolean;
  IsAutoLayout?: boolean;
  IsByRef?: boolean;
  IsByRefLike?: boolean;
  IsCOMObject?: boolean;
  IsClass?: boolean;
  IsCollectible?: boolean;
  IsConstructedGenericType?: boolean;
  IsContextful?: boolean;
  IsEnum?: boolean;
  IsExplicitLayout?: boolean;
  IsGenericMethodParameter?: boolean;
  IsGenericParameter?: boolean;
  IsGenericType?: boolean;
  IsGenericTypeDefinition?: boolean;
  IsGenericTypeParameter?: boolean;
  IsImport?: boolean;
  IsInterface?: boolean;
  IsLayoutSequential?: boolean;
  IsMarshalByRef?: boolean;
  IsNested?: boolean;
  IsNestedAssembly?: boolean;
  IsNestedFamANDAssem?: boolean;
  IsNestedFamORAssem?: boolean;
  IsNestedFamily?: boolean;
  IsNestedPrivate?: boolean;
  IsNestedPublic?: boolean;
  IsNotPublic?: boolean;
  IsPointer?: boolean;
  IsPrimitive?: boolean;
  IsPublic?: boolean;
  IsSZArray?: boolean;
  IsSealed?: boolean;
  IsSecurityCritical?: boolean;
  IsSecuritySafeCritical?: boolean;
  IsSecurityTransparent?: boolean;
  IsSerializable?: boolean;
  IsSignatureType?: boolean;
  IsSpecialName?: boolean;
  IsTypeDefinition?: boolean;
  IsUnicodeClass?: boolean;
  IsValueType?: boolean;
  IsVariableBoundArray?: boolean;
  IsVisible?: boolean;
  MemberType?: MemberTypes;
  MetadataToken?: number;
  Module?: Module;
  Name?: null | string;
  Namespace?: null | string;
  ReflectedType?: Type;
  StructLayoutAttribute?: StructLayoutAttribute;
  TypeHandle?: RuntimeTypeHandle;
  TypeInitializer?: ConstructorInfo;
  UnderlyingSystemType?: Type;
}
